
// ========================= PRODUCTS ===============================

export const products = [
  {
    id_product: 1,
    name: 'Super Pouf',
    artisan_id: 1,
    category: 'ameublement',
    type: 'pouf',
    thumbnail: '',
    photo: '../assets/01.jpg',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Limoges',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
    produit_du_mois: false,
  },
  {
    id_product: 2,
    name: 'Tabula Rasa',
    artisan_id: 2,
    category: 'ameublement',
    type: 'table',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: 'bois recyclé',
    origine: 'Paris',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
    produit_du_mois: false,
  },
  {
    id_product: 3,
    name: 'Bekvøm',
    artisan_id: 2,
    category: 'ameublement',
    type: 'tabouret',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: 'pin naturel',
    origine: 'Stokhölm',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
    produit_du_mois: false,
  },
  {
    id_product: 4,
    name: 'Fragransse',
    artisan_id: 1,
    category: 'ambiance',
    type: 'parfums',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: 'ethylpropyl',
    origine: 'Grasse',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: false,
    produit_du_mois: true,
  },
  {
    id_product: 5,
    name: 'Fragransse',
    artisan_id: 1,
    category: 'ambiance',
    type: 'parfums',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: 'ethylpropyl',
    origine: 'Grasse',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: false,
    produit_du_mois: true,
  },
  {
    id_product: 6,
    name: 'Fragransse',
    artisan_id: 1,
    category: 'ambiance',
    type: 'parfums',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: 'ethylpropyl',
    origine: 'Grasse',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: false,
    produit_du_mois: true,
  },
  {
    id_product: 7,
    name: 'Fragransse',
    artisan_id: 1,
    category: 'ambiance',
    type: 'parfums',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: 'ethylpropyl',
    origine: 'Grasse',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: false,
    produit_du_mois: true,
  },

];

// ========================= ARTISANS ===============================

export const artisans = [
  {
    id: 1,
    name: 'Willy Muller',
    presentation: 'ameublements fsdffdfdsfsdfsdf sffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Limoges',
    firstPage: true,
    portrait: true,
  },
  {
    id: 2,
    name: 'Sophie Zama',
    presentation: 'ameublementsfsd ffdfdsfsdfsdfsf fsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: true,
    portrait: false,
  },
  {
    id: 3,
    name: 'Josy Pelletier',
    presentation: 'ameublements fskj fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Auvergne',
    firstPage: false,
    portrait: false,
  },
  {
    id: 4,
    name: 'Alix Montaigne',
    presentation: 'ameublements fsdffdfdsfsd fsdfsffsfsd fsdfdsfsdf dsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Limoges',
    firstPage: false,
    portrait: false,
  },
  {
    id: 5,
    name: 'Julia Farra',
    presentation: 'ameublements fsdffdfdsfsdfs dfsffsfsd fsdfdsfsdf dsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: true,
    portrait: false,
  },
  {
    id: 6,
    name: 'Ludo Riva',
    presentation: 'ameublements fsdffdfdsfs dfsdfsffsfsd fsdfdsfsdfds fdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: true,
    portrait: false,
  },
  {
    id: 7,
    name: 'Lynda Zubi',
    presentation: 'ameublements fsdffdfdsfsdfs dfsffsfsd fsdfdsfsdfd sfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: false,
    portrait: false,
  },
  {
    id: 8,
    name: 'Pamela Rubia',
    presentation: 'ameublements fsdffdfds fsdfsdfsffsfsd fsdfdsfsdfdsfd sfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: false,
    portrait: false,
  },
  {
    id: 9,
    name: 'Silvia Cecutti',
    presentation: 'ameublements fsdffdfdsfs dfsdfsffsfsd fsdfdsfsd fdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: false,
    portrait: false,
  },
  {
    id: 10,
    name: 'Celine Fox',
    presentation: 'ameublements fsdffdfdsfsdf sdfsffsfsd fsdfdsfsdf dsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: false,
    portrait: false,
  },
];
